// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package advanced_pagination_wrapper.proxies;

public class PageHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pageHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Advanced_Pagination_Wrapper.PageHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PageNumber("PageNumber"),
		SelectAllPage("SelectAllPage"),
		PageHelper_Pagination("Advanced_Pagination_Wrapper.PageHelper_Pagination");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PageHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PageHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pageHelperMendixObject)
	{
		if (pageHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, pageHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.pageHelperMendixObject = pageHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PageHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static advanced_pagination_wrapper.proxies.PageHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return advanced_pagination_wrapper.proxies.PageHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static advanced_pagination_wrapper.proxies.PageHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new advanced_pagination_wrapper.proxies.PageHelper(context, mendixObject);
	}

	public static advanced_pagination_wrapper.proxies.PageHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return advanced_pagination_wrapper.proxies.PageHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PageNumber
	 */
	public final java.lang.Integer getPageNumber()
	{
		return getPageNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PageNumber
	 */
	public final java.lang.Integer getPageNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PageNumber.toString());
	}

	/**
	 * Set value of PageNumber
	 * @param pagenumber
	 */
	public final void setPageNumber(java.lang.Integer pagenumber)
	{
		setPageNumber(getContext(), pagenumber);
	}

	/**
	 * Set value of PageNumber
	 * @param context
	 * @param pagenumber
	 */
	public final void setPageNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pagenumber)
	{
		getMendixObject().setValue(context, MemberNames.PageNumber.toString(), pagenumber);
	}

	/**
	 * @return value of SelectAllPage
	 */
	public final java.lang.Boolean getSelectAllPage()
	{
		return getSelectAllPage(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectAllPage
	 */
	public final java.lang.Boolean getSelectAllPage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SelectAllPage.toString());
	}

	/**
	 * Set value of SelectAllPage
	 * @param selectallpage
	 */
	public final void setSelectAllPage(java.lang.Boolean selectallpage)
	{
		setSelectAllPage(getContext(), selectallpage);
	}

	/**
	 * Set value of SelectAllPage
	 * @param context
	 * @param selectallpage
	 */
	public final void setSelectAllPage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selectallpage)
	{
		getMendixObject().setValue(context, MemberNames.SelectAllPage.toString(), selectallpage);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PageHelper_Pagination
	 */
	public final advanced_pagination_wrapper.proxies.Pagination getPageHelper_Pagination() throws com.mendix.core.CoreException
	{
		return getPageHelper_Pagination(getContext());
	}

	/**
	 * @param context
	 * @return value of PageHelper_Pagination
	 * @throws com.mendix.core.CoreException
	 */
	public final advanced_pagination_wrapper.proxies.Pagination getPageHelper_Pagination(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		advanced_pagination_wrapper.proxies.Pagination result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PageHelper_Pagination.toString());
		if (identifier != null) {
			result = advanced_pagination_wrapper.proxies.Pagination.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PageHelper_Pagination
	 * @param pagehelper_pagination
	 */
	public final void setPageHelper_Pagination(advanced_pagination_wrapper.proxies.Pagination pagehelper_pagination)
	{
		setPageHelper_Pagination(getContext(), pagehelper_pagination);
	}

	/**
	 * Set value of PageHelper_Pagination
	 * @param context
	 * @param pagehelper_pagination
	 */
	public final void setPageHelper_Pagination(com.mendix.systemwideinterfaces.core.IContext context, advanced_pagination_wrapper.proxies.Pagination pagehelper_pagination)
	{
		if (pagehelper_pagination == null) {
			getMendixObject().setValue(context, MemberNames.PageHelper_Pagination.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PageHelper_Pagination.toString(), pagehelper_pagination.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pageHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final advanced_pagination_wrapper.proxies.PageHelper that = (advanced_pagination_wrapper.proxies.PageHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
