// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package advanced_pagination_wrapper.proxies;

public class Pagination
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paginationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Advanced_Pagination_Wrapper.Pagination";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PageNumber("PageNumber"),
		PageSize("PageSize"),
		ResultTotal("ResultTotal"),
		SortAscending("SortAscending"),
		SortAttribute("SortAttribute"),
		SearchType("SearchType"),
		Searched("Searched"),
		SelectAll("SelectAll");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Pagination(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Pagination(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paginationMendixObject)
	{
		if (paginationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, paginationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.paginationMendixObject = paginationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Pagination.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static advanced_pagination_wrapper.proxies.Pagination initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return advanced_pagination_wrapper.proxies.Pagination.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static advanced_pagination_wrapper.proxies.Pagination initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Advanced_Pagination_Wrapper.SearchHelper", mendixObject.getType())) {
			return advanced_pagination_wrapper.proxies.SearchHelper.initialize(context, mendixObject);
		}
		return new advanced_pagination_wrapper.proxies.Pagination(context, mendixObject);
	}

	public static advanced_pagination_wrapper.proxies.Pagination load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return advanced_pagination_wrapper.proxies.Pagination.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PageNumber
	 */
	public final java.lang.Integer getPageNumber()
	{
		return getPageNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PageNumber
	 */
	public final java.lang.Integer getPageNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PageNumber.toString());
	}

	/**
	 * Set value of PageNumber
	 * @param pagenumber
	 */
	public final void setPageNumber(java.lang.Integer pagenumber)
	{
		setPageNumber(getContext(), pagenumber);
	}

	/**
	 * Set value of PageNumber
	 * @param context
	 * @param pagenumber
	 */
	public final void setPageNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pagenumber)
	{
		getMendixObject().setValue(context, MemberNames.PageNumber.toString(), pagenumber);
	}

	/**
	 * @return value of PageSize
	 */
	public final java.lang.Long getPageSize()
	{
		return getPageSize(getContext());
	}

	/**
	 * @param context
	 * @return value of PageSize
	 */
	public final java.lang.Long getPageSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.PageSize.toString());
	}

	/**
	 * Set value of PageSize
	 * @param pagesize
	 */
	public final void setPageSize(java.lang.Long pagesize)
	{
		setPageSize(getContext(), pagesize);
	}

	/**
	 * Set value of PageSize
	 * @param context
	 * @param pagesize
	 */
	public final void setPageSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long pagesize)
	{
		getMendixObject().setValue(context, MemberNames.PageSize.toString(), pagesize);
	}

	/**
	 * @return value of ResultTotal
	 */
	public final java.lang.Integer getResultTotal()
	{
		return getResultTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultTotal
	 */
	public final java.lang.Integer getResultTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ResultTotal.toString());
	}

	/**
	 * Set value of ResultTotal
	 * @param resulttotal
	 */
	public final void setResultTotal(java.lang.Integer resulttotal)
	{
		setResultTotal(getContext(), resulttotal);
	}

	/**
	 * Set value of ResultTotal
	 * @param context
	 * @param resulttotal
	 */
	public final void setResultTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer resulttotal)
	{
		getMendixObject().setValue(context, MemberNames.ResultTotal.toString(), resulttotal);
	}

	/**
	 * @return value of SortAscending
	 */
	public final java.lang.Boolean getSortAscending()
	{
		return getSortAscending(getContext());
	}

	/**
	 * @param context
	 * @return value of SortAscending
	 */
	public final java.lang.Boolean getSortAscending(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SortAscending.toString());
	}

	/**
	 * Set value of SortAscending
	 * @param sortascending
	 */
	public final void setSortAscending(java.lang.Boolean sortascending)
	{
		setSortAscending(getContext(), sortascending);
	}

	/**
	 * Set value of SortAscending
	 * @param context
	 * @param sortascending
	 */
	public final void setSortAscending(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sortascending)
	{
		getMendixObject().setValue(context, MemberNames.SortAscending.toString(), sortascending);
	}

	/**
	 * @return value of SortAttribute
	 */
	public final java.lang.String getSortAttribute()
	{
		return getSortAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of SortAttribute
	 */
	public final java.lang.String getSortAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SortAttribute.toString());
	}

	/**
	 * Set value of SortAttribute
	 * @param sortattribute
	 */
	public final void setSortAttribute(java.lang.String sortattribute)
	{
		setSortAttribute(getContext(), sortattribute);
	}

	/**
	 * Set value of SortAttribute
	 * @param context
	 * @param sortattribute
	 */
	public final void setSortAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sortattribute)
	{
		getMendixObject().setValue(context, MemberNames.SortAttribute.toString(), sortattribute);
	}

	/**
	 * Set value of SearchType
	 * @param searchtype
	 */
	public final advanced_pagination_wrapper.proxies.ENUM_SearchType getSearchType()
	{
		return getSearchType(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchType
	 */
	public final advanced_pagination_wrapper.proxies.ENUM_SearchType getSearchType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SearchType.toString());
		if (obj == null) {
			return null;
		}
		return advanced_pagination_wrapper.proxies.ENUM_SearchType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SearchType
	 * @param searchtype
	 */
	public final void setSearchType(advanced_pagination_wrapper.proxies.ENUM_SearchType searchtype)
	{
		setSearchType(getContext(), searchtype);
	}

	/**
	 * Set value of SearchType
	 * @param context
	 * @param searchtype
	 */
	public final void setSearchType(com.mendix.systemwideinterfaces.core.IContext context, advanced_pagination_wrapper.proxies.ENUM_SearchType searchtype)
	{
		if (searchtype != null) {
			getMendixObject().setValue(context, MemberNames.SearchType.toString(), searchtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SearchType.toString(), null);
		}
	}

	/**
	 * @return value of Searched
	 */
	public final java.lang.Boolean getSearched()
	{
		return getSearched(getContext());
	}

	/**
	 * @param context
	 * @return value of Searched
	 */
	public final java.lang.Boolean getSearched(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Searched.toString());
	}

	/**
	 * Set value of Searched
	 * @param searched
	 */
	public final void setSearched(java.lang.Boolean searched)
	{
		setSearched(getContext(), searched);
	}

	/**
	 * Set value of Searched
	 * @param context
	 * @param searched
	 */
	public final void setSearched(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean searched)
	{
		getMendixObject().setValue(context, MemberNames.Searched.toString(), searched);
	}

	/**
	 * @return value of SelectAll
	 */
	public final java.lang.Boolean getSelectAll()
	{
		return getSelectAll(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectAll
	 */
	public final java.lang.Boolean getSelectAll(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SelectAll.toString());
	}

	/**
	 * Set value of SelectAll
	 * @param selectall
	 */
	public final void setSelectAll(java.lang.Boolean selectall)
	{
		setSelectAll(getContext(), selectall);
	}

	/**
	 * Set value of SelectAll
	 * @param context
	 * @param selectall
	 */
	public final void setSelectAll(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selectall)
	{
		getMendixObject().setValue(context, MemberNames.SelectAll.toString(), selectall);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paginationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final advanced_pagination_wrapper.proxies.Pagination that = (advanced_pagination_wrapper.proxies.Pagination) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
