// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package advanced_pagination_wrapper.proxies;

public class Search
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Advanced_Pagination_Wrapper.Search";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NameToSearch("NameToSearch"),
		NameToSearch_Filter("NameToSearch_Filter"),
		Search_SearchHelper("Advanced_Pagination_Wrapper.Search_SearchHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Search(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Search(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchMendixObject)
	{
		if (searchMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, searchMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.searchMendixObject = searchMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Search.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static advanced_pagination_wrapper.proxies.Search initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return advanced_pagination_wrapper.proxies.Search.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static advanced_pagination_wrapper.proxies.Search initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new advanced_pagination_wrapper.proxies.Search(context, mendixObject);
	}

	public static advanced_pagination_wrapper.proxies.Search load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return advanced_pagination_wrapper.proxies.Search.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NameToSearch
	 */
	public final java.lang.String getNameToSearch()
	{
		return getNameToSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of NameToSearch
	 */
	public final java.lang.String getNameToSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NameToSearch.toString());
	}

	/**
	 * Set value of NameToSearch
	 * @param nametosearch
	 */
	public final void setNameToSearch(java.lang.String nametosearch)
	{
		setNameToSearch(getContext(), nametosearch);
	}

	/**
	 * Set value of NameToSearch
	 * @param context
	 * @param nametosearch
	 */
	public final void setNameToSearch(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nametosearch)
	{
		getMendixObject().setValue(context, MemberNames.NameToSearch.toString(), nametosearch);
	}

	/**
	 * @return value of NameToSearch_Filter
	 */
	public final java.lang.String getNameToSearch_Filter()
	{
		return getNameToSearch_Filter(getContext());
	}

	/**
	 * @param context
	 * @return value of NameToSearch_Filter
	 */
	public final java.lang.String getNameToSearch_Filter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NameToSearch_Filter.toString());
	}

	/**
	 * Set value of NameToSearch_Filter
	 * @param nametosearch_filter
	 */
	public final void setNameToSearch_Filter(java.lang.String nametosearch_filter)
	{
		setNameToSearch_Filter(getContext(), nametosearch_filter);
	}

	/**
	 * Set value of NameToSearch_Filter
	 * @param context
	 * @param nametosearch_filter
	 */
	public final void setNameToSearch_Filter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nametosearch_filter)
	{
		getMendixObject().setValue(context, MemberNames.NameToSearch_Filter.toString(), nametosearch_filter);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Search_SearchHelper
	 */
	public final advanced_pagination_wrapper.proxies.SearchHelper getSearch_SearchHelper() throws com.mendix.core.CoreException
	{
		return getSearch_SearchHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Search_SearchHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final advanced_pagination_wrapper.proxies.SearchHelper getSearch_SearchHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		advanced_pagination_wrapper.proxies.SearchHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Search_SearchHelper.toString());
		if (identifier != null) {
			result = advanced_pagination_wrapper.proxies.SearchHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Search_SearchHelper
	 * @param search_searchhelper
	 */
	public final void setSearch_SearchHelper(advanced_pagination_wrapper.proxies.SearchHelper search_searchhelper)
	{
		setSearch_SearchHelper(getContext(), search_searchhelper);
	}

	/**
	 * Set value of Search_SearchHelper
	 * @param context
	 * @param search_searchhelper
	 */
	public final void setSearch_SearchHelper(com.mendix.systemwideinterfaces.core.IContext context, advanced_pagination_wrapper.proxies.SearchHelper search_searchhelper)
	{
		if (search_searchhelper == null) {
			getMendixObject().setValue(context, MemberNames.Search_SearchHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Search_SearchHelper.toString(), search_searchhelper.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final advanced_pagination_wrapper.proxies.Search that = (advanced_pagination_wrapper.proxies.Search) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
