// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package advanced_pagination_wrapper.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the Advanced_Pagination_Wrapper module

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Advanced_Pagination_Wrapper.LogNode");
	}

	public static java.lang.String getPagination_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Advanced_Pagination_Wrapper.Pagination_Version");
	}
}