// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package utility.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Utility module
	public static void aCT_CreateMultipleItems(IContext context, utility.proxies.CreateItems _createItems)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CreateItems", _createItems == null ? null : _createItems.getMendixObject());
		Core.microflowCall("Utility.ACT_CreateMultipleItems").withParams(params).execute(context);
	}
	public static void aCT_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Utility.ACT_DeleteAll").withParams(params).execute(context);
	}
	public static java.util.List<advanced_pagination_wrapper.proxies.SelectionHelper> dS_ShowSelectedItems(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Utility.DS_ShowSelectedItems").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> advanced_pagination_wrapper.proxies.SelectionHelper.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
}
